/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.nlpcraft.model.tools.sqlgen;

import org.apache.nlpcraft.model.NCModel;
import org.apache.nlpcraft.model.tools.sqlgen.impl.NCSqlExtractorsImpl;

/**
 * Builds object presentation of SQL schema for given data model. Data model must be
 * generated by {@link NCSqlModelGenerator} class.
 *
 * @see NCSqlModelGenerator
 * @see NCSqlExtractors
 */
public class NCSqlSchemaBuilder {
    /**
     * Builds object presentation for SQL schema from given data model.
     *
     * @param model Data model to generate object SQL schema presentation. Note that the model must be
     *      generated by {@link NCSqlModelGenerator} class.
     * @return Object presentation of the SQL schema for a given data model.
     * @throws NCSqlException Thrown in case of any errors.
     * @see NCSqlModelGenerator
     */
    public static NCSqlSchema makeSchema(NCModel model) {
        return NCSqlExtractorsImpl.makeSchema(model);
    }
}
